version: '3'

services:
  drfsample:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    command: bash -c "python manage.py makemigrations movies && python manage.py migrate && gunicorn -w 2 -b 0.0.0.0:80 drfsample.wsgi"
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - .:/app