version: '3'

services:
  drfsample:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    command: bash -c "python manage.py makemigrations movies && python manage.py migrate && gunicorn -w 2 -b 0.0.0.0:8000 drfsample.wsgi"
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - .:/app